export const INVENTORY_IMAGES = {
	summary: require("./summary.png"),
	transfer: require("./transfer.png"),
	adjustment: require("./adjustment.png"),
	material: require("./material.png"),
	composition: require("./composition.png"),
	purchase: require("./purchase.png"),
	supplier: require("./supplier.png"),
	payment: require("./payment.png"),
	movement: require("./movement.png"),
	closing: require("./closing.png"),
	katsu: require("./katsu.png"),
	ayam: require("./ayam.png"),
	mie: require("./mie.png"),
	fillet: require("./fillet.png"),
	minyak: require("./minyak.png"),
	gula: require("./gula.png"),
	tepung: require("./tepung.png"),
};
